# version: "4.0.0"

services:
  countries_game:
    build:
      context: .
      dockerfile: Dockerfile
    image: countries_game
    container_name: countries_game
    hostname: countries_game
    ports:
      - "0.0.0.0:3000:80"
    volumes:
      - .:/app
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=countries_game_db
      - DB_PORT=3306
      - DB_DATABASE=countries_game
      - DB_USERNAME=admin
      - DB_PASSWORD=A9x*UwARA5@
    depends_on:
      countries_game_db:
        condition: service_healthy
    command: >
      sh -c "php artisan serve --host=0.0.0.0 --port=80"

  countries_game_db:
    image: mysql:latest
    container_name: countries_game_db
    hostname: countries_game_db
    ports:
        - "3305:3306" # Host:Container
    environment:
        - MYSQL_DATABASE=countries_game
        - MYSQL_USER=admin
        - MYSQL_PASSWORD=A9x*UwARA5@
        - MYSQL_ROOT_PASSWORD=Aa101985$
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  db-data:
